version: '3.4'

services:
  mysql:
    container_name: mysql  
    image: mysql:5.7.28
    restart: always
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ROOT_HOST: '%'
    command: [
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci',
        '--lower_case_table_names=1'
        ]
    volumes:
        - "${APP_DIR}/data:/var/lib/mysql"
    networks:
        - nat-network
  server:
    image: ${DOCKER_REGISTRY-}discuzxnet
    depends_on:
        - mysql
    links:
        - mysql
    volumes:
        - "${APP_DIR}/appsettings.Production.json:/app/appsettings.Production.json"
        - "${APP_DIR}/appdata:/app/wwwroot"
    networks:
      - nat-network

networks: 
  nat-network:
      driver:  bridge
